### ISSUE TITLE
Status of this module

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/d2b_migrate#1]
We are planning a Drupal 7 EOL sprint at Badcamp (2022) with the goal of making it easier for Drupal 7 sites to upgrade to Backdrop CMS. One core issue that we are interested in is this one:

https://github.com/backdrop/backdrop-issues/issues/4345

It has been suggested that the work @docwilmot started here might be a good step in that direction (the above mentioned issue). 

I've not had time to test this module, but am wondering if testing this module might be a good thing to do in this upcoming Sprint. But, before asking anyone to take time and test this module it seems worth asking if it's ready to be tested and/or if there is anything else we should consider before using this module.

**Comment by docwilmot** [comment]
This is alpha at most. It was done quickly and havent looked at it since 1yr.

Having said, I think the concept is a good template to work on. AFAICR the two flakiest bits are:
- importing files. I put in a temporary workaround that uses the managed files tables, but this is unsatisfactory as lots of files (logo for example) may not be managed.
- forcing the site to immediately run update.php after importing the DB. This must be done, because otherwise youre trying to run a Backdrop site with a D7 DB, but I recall struggling to make that happen. Think I managed with some crutches and an `exit()` call.

I'm sure testing will highlight lots of other interesting bugs. There are absolutely no security considerations in place. Keep in mind also that this is doing funny things with creating directories, slinging files around and deleting databases. I would be unsurprised if someone's computer was rendered unusable while using this. Fair warning.
