### ISSUE TITLE
In step d2b-migrate/analysis module times out

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/d2b_migrate#9]
I am testing module on Pantheon using reasonably simple site as a source and get message "The application did not respond in time."  
Log shows 
`PDOException: SQLSTATE[HY000] [2002] Connection timed out in d2b_migrate_analysis_fetch_projects() (line 509 of /code/modules/d2b_migrate-main/d2b_migrate.module).`

I can run backdrop update status for this site from D7 without any problems.  
I am not sure how to approach this problem - thanks in advance for any pointers.

**Comment by juanolalla** [comment]
@irinaz This looks like it's happening to you after clicking the "Update project data" button in the analysis part. The connection is failing and throwing an exception, but there wasn't any check for this possibility at this points, because the module already checks the connection in the step before. I'm adding a try-catch to handle this possibility in the Update project data submit as well (https://github.com/juanolalla/d2b_migrate/commit/fcee4f932ab2b654b2c1fe52cf2636d44e3c7f9c --> I'm making a pull request with this).

And why did this passed the connection check in the previous step? I've been working with the Backdrop site in Pantheon you gave me access to, and I've seen that check in the validate process was overridden and a database data was harcoded there. And database connection does work.

I've restored that part in your code and committed along with the changes in the referenced commit above. And I've tried then with the database data that was harcoded in the code, and it works. I guess that's probably yours from other project. Not sure why this one works and the other doesn't. I'll give you this data in private.

**Comment by irinaz** [comment]
@juanolalla , this is great success - I was able to download projects.  The next step that I do is "backup database" and I get weird message `"PDOException: SQLSTATE[HY000] [2002] Connection refused in backup_migrate_source_db->_get_db_connection() (line 235 of /code/modules/backup_migrate/includes/sources.db.inc)." ` It is confusing because I am connecting to the same database - I was able to connect successfully in step Database Analysis.
Let me know if you can see what might be an issue!  Thanks a lot!

**Comment by irinaz** [comment]
@docwilmot , the change related to db version has been completed in core release, so now these changes can be merged.   Thanks a lot, Irina

**Comment by stpaultim** [comment]
@docwilmot - Sorry to bug you, but we're hoping to work on thsi tomorrow. Is this something that we can merge?

**Comment by docwilmot** [comment]
I believe I merged this a while ago but didnt comment here. Can close the issue once its tested and working.

**Comment by stpaultim** [comment]
Thanks @docwilmot. Hopefully, we will have time to confirm this today.

**Comment by docwilmot** [comment]
Would be great to have further tests, thanks.

**Comment by irinaz** [comment]
I have tested this step with various sites and db,  this step works great.
